/*# autoGenerated */
interface ccsi_test_table_two extends sys_metadata {
  name: string;
  user: sys_user;
  active: boolean;
  description: string;
}
/*# sourceMappingURL=ccsi_test_table_two.xml.ts.map */