/*# autoGenerated */
namespace global {
  class $aaaabbbbccccddddeeeeffff00001111 extends sys_app {
    active = true;
    can_edit_in_studio = "false";
    enforce_license = "none";
    guided_setup_guid = undefined;
    installed_as_dependency = "false";
    js_level = "es_latest";
    licensable = "true";
    license = undefined;
    license_category = "none";
    license_definition = undefined;
    license_model = "none";
    logo = undefined;
    menu = undefined;
    name = "DVA POC";
    package_json = undefined;
    private = "false";
    restrict_table_access = "false";
    runtime_access_tracking = undefined;
    scope = "sn_dva_poc";
    scoped_administration = "false";
    short_description = "poc";
    source = "sn_dva_poc";
    store_correlation_id = undefined;
    store_url = undefined;
    subscription_entitlement = undefined;
    sys_class_name = "sys_app";
    sys_code = undefined;
    sys_created_by = "maint";
    sys_created_on = "2024-02-05 21:47:40";
    sys_id = "aaaabbbbccccddddeeeeffff00001111";
    sys_mod_count = "0";
    sys_updated_by = "maint";
    sys_updated_on = "2024-02-05 00:00:00";
    template = undefined;
    trackable = "true";
    uninstall_blocked = "false";
    user_role = undefined;
    vendor = undefined;
    vendor_prefix = undefined;
    version = "1.0.0";
  }
}
/*# sourceMappingURL=sys_app_aaaabbbbccccddddeeeeffff00001111.xml.ts.map */