/*# autoGenerated */
namespace sn_dva_poc {
  class $fde8f731dbb933004005b12c4e961964 extends sys_security_acl {
    active = true;
    admin_overrides = "true";
    advanced = "true";
    condition = new GlideElement({ table: "MisMatchedACLProcessor", value: undefined });
    description = undefined;
    name = "MisMatchedACLProcessor";
    operation = new GlideElement({ display_value: "execute", value: "execute" });
    script = () => {
answer = false;

if (gs.isLoggedIn())
	answer = true;

if (pm.isRegistered("com.glide.explicit_roles") && gs.getProperty("glide.security.use_explicit_roles", "false") == "true")
	answer = true;
    };
    sys_class_name = "sys_security_acl";
    sys_created_by = "ismail.aydemir@snc";
    sys_created_on = "2019-06-03 19:14:01";
    sys_id = "fde8f731dbb933004005b12c4e961964";
    sys_mod_count = "0";
    sys_name = "MisMatchedACLProcessor";
    sys_package = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC", source: "sn_dva_poc" */;
    sys_policy = undefined;
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_update_name = "sys_security_acl_fde8f731dbb933004005b12c4e961964";
    sys_updated_by = "ismail.aydemir@snc";
    sys_updated_on = "2019-06-03 19:14:01";
    type = new GlideElement({ display_value: "processor", value: "processor" });
  }
}
/*# sourceMappingURL=sys_security_acl_8f731dbb933004005b12c4e961964.xml.ts.map */