/*# autoGenerated */
namespace sn_dva_poc {
  class $rfor_nonpublic_aclprotected extends sys_security_acl_role {
    sys_id = "rfor_nonpublic_aclprotected";
    sys_class_name = "sys_security_acl_role";
    sys_created_by = "admin";
    sys_created_on = "2023-05-19 15:49:14";
    sys_mod_count = "0";
    sys_name = ".itil";
    sys_package = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC", source: "sn_dva_poc" */;
    sys_policy = undefined;
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_security_acl = new GlideElement({ display_value: "for_nonpublic_aclprotected", value: "for_nonpublic_aclprotected" });
    sys_update_name = "sys_security_acl_rfor_nonpublic_aclprotected";
    sys_updated_by = "admin";
    sys_updated_on = "2023-05-19 15:49:14";
    sys_user_role = new GlideElement({ display_value: "itil", name: "itil", value: "282bf1fac6112285017366cb5f867469" });
    transaction_id = undefined;
  }
}
/*# sourceMappingURL=sys_security_acl_role_rfor_nonpublic_aclprotected.xml.ts.map */