/*# autoGenerated */
namespace sn_dva_poc {
  class $MisMatchedACLProcessor extends sys_processor {
    active = true;
    class_name = "\ncom.snc.platform.security.oauth.processor.OAuthJWKSProcessor\n";
    description = "\nServes the JSON Web Key Set containing the public keys used to verify signatures on issued JWT tokens.\n";
    interactive = "false";
    name = "MisMatchedACLProcessor";
    parameters = undefined;
    params_endpoint = undefined;
    path = "oauth_jwks";
    path_endpoint = undefined;
    require_csrf = "false";
    roles = undefined;
    script = undefined;
    sys_class_name = "sys_processor";
    sys_created_by = "admin";
    sys_created_on = "2025-07-24 11:49:33";
    sys_id = "MisMatchedACLProcessor";
    sys_mod_count = "0";
    sys_name = "MisMatchedACLProcessor";
    sys_package = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC", source: "sn_dva_poc" */;
    sys_policy = undefined;
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_update_name = "sys_processor_MisMatchedACLProcessor";
    sys_updated_by = "admin";
    sys_updated_on = "2025-07-24 11:49:33";
    type = "java";
    xframe_sameorigin = "false";
  }
}
/*# sourceMappingURL=sys_processor_MisMatchedACLProcessor.xml.ts.map */