/*# autoGenerated */
namespace com.snc.service {
  class $282bf1fac6112285017366cb5f867469 extends sys_user_role {
    description = "Can perform standard actions for an ITIL helpdesk technician. This is the ''technician'' role. Can open, update, close incidents, problems, changes, configuration management items. By default, only users with the \"itil\" role can have tasks assigned to them.";
    grantable = "true";
    includes_roles = "template_editor,approver_user";
    name = "itil";
    snbe = "false";
    suffix = undefined;
    sys_class_name = "sys_user_role";
    sys_created_by = "fred.luddy";
    sys_created_on = "2005-02-19 01:12:11";
    sys_customer_update = "false";
    sys_id = "282bf1fac6112285017366cb5f867469";
    sys_mod_count = "3";
    sys_name = "itil";
    sys_package = $7776c92cdb4812004ab69aefe0b8f512 /* display_value: "Service Management Basics", source: "com.snc.service" */;
    sys_policy = undefined;
    sys_replace_on_upgrade = "false";
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_update_name = "sys_user_role_282bf1fac6112285017366cb5f867469";
    sys_updated_by = "chandra.mudili";
    sys_updated_on = "2015-11-27 11:27:40";
  }
}
/*# sourceMappingURL=sys_user_role_282bf1fac6112285017366cb5f867469.xml.ts.map */