/*# autoGenerated */
namespace sn_dva_poc {
  class $0000withScript extends sys_security_acl {
    sys_id = "0000withScript";
    sys_update_name = "sys_security_acl_0000withScript";
    name = "non_existant_table";
    sys_name = "non_existant_table";
    active = true;
    admin_overrides = "true";
    advanced = "true";
    condition = undefined;
    description = "Should have no role No Attribute, no Condition";
    script = "answer = gs.hasRole('admin')";
    type = new GlideElement({ display_value: "record", value: "record" });
    operation = new GlideElement({ display_value: "read", value: "read" });
    sys_class_name = "sys_security_acl";
    sys_created_by = "admin";
    sys_created_on = "2017-09-28 13:23:16";
    sys_mod_count = "0";
    sys_package = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC", source: "sn_dva_poc" */;
    sys_policy = undefined;
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_updated_by = "admin";
    sys_updated_on = "2017-09-28 13:23:16";
  }
}
/*# sourceMappingURL=sys_security_acl_0000withScript.xml.ts.map */