/*# autoGenerated */
namespace sn_dva_poc {
  class $write_for_ccsi_test_table extends sys_security_acl {
    name = "ccsi_test_table";
    sys_name = "ccsi_test_table";
    sys_id = "write_for_ccsi_test_table";
    sys_update_name = "sys_security_acl_write_for_ccsi_test_table";
    operation = new GlideElement({ display_value: "write", value: "write" });
    active = true;
    admin_overrides = "true";
    advanced = "false";
    condition = undefined;
    description = undefined;
    script = () => {
answer = gs.hasRole("itil"); // the same as the role relation
    };
    sys_class_name = "sys_security_acl";
    sys_created_by = "admin";
    sys_created_on = "2017-09-28 13:23:16";
    sys_mod_count = "0";
    sys_package = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC", source: "sn_dva_poc" */;
    sys_policy = undefined;
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_updated_by = "admin";
    sys_updated_on = "2017-09-28 13:23:16";
    type = new GlideElement({ display_value: "record", value: "record" });
  }
}
/*# sourceMappingURL=sys_security_acl_write_for_ccsi_test_table.xml.ts.map */