/*# autoGenerated */
namespace sn_dva_poc {
  class $for_nonpublic_aclprotected extends sys_security_acl {
    sys_id = "for_nonpublic_aclprotected";
    active = true;
    admin_overrides = "true";
    advanced = "false";
    condition = new GlideElement({ table: "NonpublicAclProtected", value: undefined });
    description = undefined;
    local_or_existing = undefined;
    name = "NonpublicAclProtected";
    operation = new GlideElement({ display_value: "execute", value: "execute" });
    script = undefined;
    security_attribute = new GlideElement({ display_value: "", value: undefined });
    sys_class_name = "sys_security_acl";
    sys_created_by = "admin";
    sys_created_on = "2023-05-19 15:49:14";
    sys_mod_count = "0";
    sys_name = "NonpublicAclProtected";
    sys_package = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC", source: "sn_dva_poc" */;
    sys_policy = undefined;
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_update_name = "sys_security_acl_for_nonpublic_aclprotected";
    sys_updated_by = "admin";
    sys_updated_on = "2023-05-19 15:49:14";
    type = new GlideElement({ display_value: "client_callable_script_include", value: "client_callable_script_include" });
  }
}
/*# sourceMappingURL=sys_security_acl_for_nonpublic_aclprotected.xml.ts.map */