/*# autoGenerated */
namespace sn_dva_poc {
  class $nonpublic_noacl extends sys_script_include {
    access = "package_private";
    active = true;
    api_name = "global.NonpublicNoACL";
    caller_access = undefined;
    client_callable = "true";
    description = undefined;
    name = "NonpublicNoACL";
    script = () => {
var NonpublicNoACL = Class.create();
NonpublicNoACL.prototype = Object.extendsObject(AbstractAjaxProcessor, {
	exfilSomeData: function() {
	    var columnName = this.getParameter('sysparm_columnname');

	    var dynamicGr = new GlideRecord('ccsi_test_table');
	    dynamicGr.query();
	    dynamicGr.next();

	    return dynamicGr.getValue(columnName);
	},
	exfilSomeDataTwo: function() {
	    var columnName = this.getParameter('sysparm_columnname');

	    var dynamicGr = new GlideRecord('ccsi_test_table_two');
	    dynamicGr.query();
	    dynamicGr.next();

	    return dynamicGr.getValue(columnName);
	},
	nonDynamic: function() {
	    var nondynamicGr = new GlideRecord('ccsi_test_table');
	    nondynamicGr.query();
	    nondynamicGr.next();

	    return nondynamicGr.getValue('name');
	},
	someUpdate: function() {
	    return this.someUpdateTwo(getParameter('sysparm_input'));
	},
	someUpdateTwo: function(someArg) {
	    var gr = new GlideRecord('ccsi_test_table');
	    gr.query();
	    if(gr.next()) {
	        gr.setValue('name', someArg);
            return gr.update();
	    }
	    return false
	},
	type: 'NonpublicNoACL'
});
    };
    sys_class_name = "sys_script_include";
    sys_created_by = "admin";
    sys_created_on = "2023-05-16 18:10:53";
    sys_id = "nonpublic_noacl";
    sys_mod_count = "0";
    sys_name = "NonpulbicNoACL";
    sys_package = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC", source: "sn_dva_poc" */;
    sys_policy = undefined;
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_update_name = "sys_script_include_nonpublic_noacl";
    sys_updated_by = "admin";
    sys_updated_on = "2023-05-16 18:10:53";
  }
  export function __NonpublicNoACL() { return $nonpublic_noacl };
}
/*# sourceMappingURL=sys_script_include_nonpublic_noacl.xml.ts.map */