/*# autoGenerated */
namespace sn_dva_poc {
  class $write_role_for_ccsi_test_table extends sys_security_acl_role {
    sys_id = "write_role_for_ccsi_test_table";
    sys_security_acl = new GlideElement({ display_value: "ccsi_test_table", value: "write_for_ccsi_test_table" });
    sys_update_name = "sys_security_acl_write_role_for_ccsi_test_table";
    sys_name = ".itil";
    sys_user_role = new GlideElement({ display_value: "itil", name: "itil", value: "282bf1fac6112285017366cb5f867469" });
    transaction_id = undefined;
    sys_class_name = "sys_security_acl_role";
    sys_created_by = "admin";
    sys_created_on = "2023-05-19 15:49:14";
    sys_mod_count = "0";
    sys_package = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC", source: "sn_dva_poc" */;
    sys_policy = undefined;
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_updated_by = "admin";
    sys_updated_on = "2023-05-19 15:49:14";
  }
}
/*# sourceMappingURL=sys_security_acl_write_role_for_ccsi_test_table.xml.ts.map */