/*# autoGenerated */
namespace sn_dva_poc {
  class $nonpublic_aclprotected extends sys_script_include {
    access = "package_private";
    active = true;
    api_name = "global.NonpublicAclProtected";
    caller_access = undefined;
    client_callable = "true";
    description = undefined;
    name = "NonpublicAclProtected";
    script = () => {
var NonpublicAclProtected = Class.create();
NonpublicAclProtected.prototype = Object.extendsObject(AbstractAjaxProcessor, {
	exfilSomeData: function() { // we should know that to call this, acl `for_nonpublic_aclprotected` must pass
	    var columnName = this.getParameter('sysparm_columnname');

	    var dynamicGr = new GlideRecord('ccsi_test_table');
	    dynamicGr.query();
	    dynamicGr.next();

	    return dynamicGr.getValue(columnName);
	},
	exfilSomeDataTwo: function() {
	    var columnName = this.getParameter('sysparm_columnname');

	    var dynamicGr = new GlideRecord('ccsi_test_table_two');
	    dynamicGr.query();
	    dynamicGr.next();

	    return dynamicGr.getValue(columnName);
	},
	nonDynamic: function() {
	    var nondynamicGr = new GlideRecord('ccsi_test_table');
	    nondynamicGr.query();
	    nondynamicGr.next();

	    return nondynamicGr.getValue('name');
	},
	someUpdate: function() {
	    return this.someUpdateTwo(getParameter('sysparm_input'));
	},
	someUpdateTwo: function(someArg) {
	    var gr = new GlideRecord('ccsi_test_table');
	    gr.query();
	    if(gr.next()) {
	        gr.setValue('name', someArg);
	        gr.other = getParameter('sysparm_other');
            return gr.update();
	    }
	    return false
	},
	someUpdateThree: function() {
	    var gr = new GlideRecord('ccsi_test_table');
	    gr.addQuery('name', getParameter('sysparm_name'));
        gr.query();
        if(gr.next()) {
            gr.setValue('col', getParameter('sysparm_col'));
            return gr.update();
        }
        return false;
	},
	someDelete: function() {
	    var gr = new GlideRecord('ccsi_test_table');
	            gr.addQuery('name', getParameter('sysparm_name'));
        gr.query();

        if(gr.next()) {
            return gr.deleteRecord();
        }
        return false;
    },
    someDeleteTwo: function(tableName) {
        var gr = new GlideRecord(tableName);
        gr.query();
        if(gr.next()) {
            return gr.deleteRecord();
        }
        return false;
    },
    someDeleteThree: function() {
       return this.someDeleteTwo('ccsi_test_table');
    },
	type: 'NonpublicAclProtected'
});
    };
    sys_class_name = "sys_script_include";
    sys_created_by = "admin";
    sys_created_on = "2023-05-16 18:10:53";
    sys_id = "nonpublic_aclprotected";
    sys_mod_count = "0";
    sys_name = "NonpublicAclProtected";
    sys_package = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC", source: "sn_dva_poc" */;
    sys_policy = undefined;
    sys_scope = $aaaabbbbccccddddeeeeffff00001111 /* display_value: "DVA POC" */;
    sys_update_name = "sys_script_include_nonpublic_aclprotected";
    sys_updated_by = "admin";
    sys_updated_on = "2023-05-16 18:10:53";
  }
  export function __NonpublicAclProtected() { return $nonpublic_aclprotected };
}
/*# sourceMappingURL=sys_script_include_nonpublic_aclprotected.xml.ts.map */